easy_admin:
    site_name: 'TedX Admin'
    formats:
        datetime: 'd/M/yy H:m'
    design:
        menu:
            - {entity: 'Talks', icon: 'microphone'}
            - {entity: 'Articles', icon: 'newspaper'}
            - {entity: 'Speakers', icon: 'street-view'}
            - {entity: 'Tags', icon: 'hashtag'}
            - {entity: 'Equipe', icon: 'users'}
            - {entity: 'Partenaires', icon: 'handshake'}
            - {entity: 'Banniere', icon: 'flag'}
            - {entity: 'Avis', icon: 'comments'}
            - {entity: 'Edito', icon: 'edit'}
            - {entity: 'Statistiques', icon: 'chart-bar'}
            - {entity: 'NewsLetter', icon: 'envelope-open-text'}
            - {entity: 'Contact', icon: 'address-book'}
            - {entity: 'Categorie_Partenaires', icon: 'archive'}
            - {entity: 'Categorie_Equipes', icon: 'archive'}
            - {entity: 'Mentions_Legales', icon: 'copyright'}
    entities:
        Talks:
            class: App\Entity\Talk
            list:
                actions:
                    - { name: 'youtube_talk', type: 'route', label: 'Youtube', icon: 'video', css_class: 'btn btn-dark', target: '_blank' }
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'ispublished', type: 'toggle', label: 'Publié' }
                    - { property: 'photo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'title', label: 'Titre' }
                    - 'speakers'
                    - 'tags'
                    - { property: 'created_at', label: 'Date' }
            edit:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }
                    - 'video'
                    - 'speakers'
                    - 'tags'
                    - { property: 'content', label: 'Contenu' }
            form:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }
                    - 'video'
                    - { property: 'speakers', type_options: { by_reference: false }}
                    - { property: 'tags', type_options: { by_reference: false }}
                    - { property: 'content', label: 'Contenu' }

        Articles:
            class: App\Entity\Article
            list:
                actions:
                    - { name: 'youtube_article', type: 'route', label: 'Youtube', icon: 'video', css_class: 'btn btn-dark', target: '_blank' }
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'ispublished', type: 'toggle', label: 'Publié' }
                    - { property: 'photo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
            edit:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
                    - 'video'
                    - { property: 'content', label: 'Contenu' }
            form:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Auteur' }
                    - 'video'
                    - { property: 'content', label: 'Contenu' }

        Speakers:
            class: App\Entity\Speaker
            list:
                actions:
                    - { name: 'linkedin_speaker', type: 'route', label: 'Linkedin', icon: 'link', css_class: 'btn btn-dark', target: '_blank' }
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'photo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'talks', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'talks', type_options: { by_reference: false }}
            form:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'talks', type_options: { by_reference: false }}

        Tags:
            class: App\Entity\Tag
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'talks', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'talks', type_options: { by_reference: false }}
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'talks', type_options: { by_reference: false }}

        Equipe:
            class: App\Entity\Team
            list:
                actions:
                    - { name: 'linkedin_team', type: 'route', label: 'Linkedin', icon: 'link', css_class: 'btn btn-dark', target: '_blank' }
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'photo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: true }}
            form:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'job', label: 'Métier' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: false }}

        Partenaires:
            class: App\Entity\Partner
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'logo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'logoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: true }}
            form:
                fields:
                    - { property: 'logoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'category', label: 'Catégorie', type_options: { by_reference: false }}

        Banniere:
            class: App\Entity\Banner
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'photo', type: 'image', base_path: "%uploads_path%" }
                    - { property: 'title', label: 'Titre' }
            edit:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }
            form:
                fields:
                    - { property: 'photoFile', type: 'vich_image', label: 'Fichier photo' }
                    - { property: 'title', label: 'Titre' }

        Avis:
            class: App\Entity\Feedback
            disabled_actions: ['new','edit']
            list:
                actions:
                    - { name: 'show', icon: 'eye', label: 'Voir', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'ispublished', type: 'toggle', label: 'Publié' }
                    - { property: 'comment', label: 'Commentaire' }
                    - { property: 'name', label: 'Auteur' }
                    - { property: 'job', label: 'Métier' }
            edit:
                fields:
                    - { property: 'comment', label: 'Commentaire' }
                    - { property: 'name', label: 'Auteur' }
                    - { property: 'job', label: 'Métier' }
            form:
                fields:
                    - { property: 'comment', label: 'Commentaire' }
                    - { property: 'name', label: 'Auteur' }
                    - { property: 'job', label: 'Métier' }

        Edito:
            class: App\Entity\Edito
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'content', label: 'Contenu' }
            edit:
                fields:
                    - { property: 'content', label: 'Contenu' }
            form:
                fields:
                    - { property: 'content', label: 'Contenu' }

        Statistiques:
            class: App\Entity\Stats
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'attendees', label: 'Participants' }
                    - { property: 'speakers', label: 'Speakers' }
            edit:
                fields:
                    - { property: 'attendees', label: 'Participants' }
                    - { property: 'speakers', label: 'Speakers' }
            form:
                fields:
                    - { property: 'attendees', label: 'Participants' }
                    - { property: 'speakers', label: 'Speakers' }

        NewsLetter:
            class: App\Entity\Newsletter
            disabled_actions: ['new','edit']
            list:
                actions:
                    - { name: 'show', icon: 'eye', label: 'Voir', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'email', type: 'email' }
            edit:
                fields:
                    - { property: 'email', type: 'email' }
            form:
                fields:
                    - { property: 'email', type: 'email' }

        Contact:
            class: App\Entity\Contact
            disabled_actions: ['new','edit']
            list:
                actions:
                    - { name: 'show', icon: 'eye', label: 'Voir', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', type: 'email' }
                    - { property: 'subject', label: 'Sujet' }
                    - { property: 'created_at', label: 'Date' }
            show:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'email', type: 'email' }
                    - { property: 'subject', label: 'Sujet' }
                    - 'message'
                    - { property: 'created_at', label: 'Date' }

        Categorie_Partenaires:
            class: App\Entity\CategoryPartner
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'name', label: 'Nom/Année' }
                    - { property: 'partners', label: 'Partenaires', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'partners', label: 'Partenaire', type_options: { by_reference: false }}
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'partners', label: 'Partenaire', type_options: { by_reference: false }}


        Categorie_Equipes:
            class: App\Entity\CategoryTeam
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'teams', label: 'Equipes', type_options: { by_reference: false }}
            edit:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'teams', label: 'Equipe', type_options: { by_reference: false }}
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'teams', label: 'Equipe', type_options: { by_reference: false }}

        Mentions_Legales:
            class: App\Entity\LegalMentions
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
                    - { name: 'delete', icon: 'trash-alt', label: 'Suppr', css_class: 'btn btn-danger' }
                    - { name: 'new', icon: 'plus', label: 'Ajouter', css_class: 'btn btn-success' }
                fields:
                    - { property: 'content', label: 'Contenu' }
            edit:
                fields:
                    - { property: 'content', label: 'Contenu' }
            form:
                fields:
                    - { property: 'content', label: 'Contenu' }




